### ISSUE TITLE
Errors not showing up

### ISSUE THREAD

**Issue by GideonWolfe** [neoclide/coc-eslint#26]
I got the coc-nvim plugin installed, as well as coc-eslint installed and pointed at the correct `node_modules` directory.

Coc logs suggest that eslint started just fine.

But Whatever I do, I cannot get coc to highlight an error. It works well for other languages. I have tried writing the file, closing it and reopening it, switching modes, etc.

But if I deliberately type gibberish it will not highlight as an error. Am I missing something in my config?

**Comment by chemzqm** [comment]
Check the output of language server, could be wrong filetype

**Comment by GideonWolfe** [comment]
Looks like I can now see eslint errors after I ran `eslint --init` (which had to be in my project directory). Any way to make it global? Also it recognizes some minor style corrections but still wont highlight gibberish as an error

**Comment by fannheyward** [comment]
> Any way to make it global?

If you have a configuration file in your home directory (generally ~/), ESLint uses it only if ESLint cannot find any other configuration file.

**Comment by jeffschwartz** [comment]
I can confirm this is still an issue. I intentionally removed a semi colon from an expression (see image below) and my .eslintrc.json file always requires semicolons.

![Screen Shot 2019-11-04 at 10 56 43 PM](https://user-images.githubusercontent.com/271288/68177514-8844ee80-ff56-11e9-8479-503e35cde275.png)

Here's my .eslintrc.json file:
![Screen Shot 2019-11-04 at 10 59 42 PM](https://user-images.githubusercontent.com/271288/68177605-d1953e00-ff56-11e9-9a1f-67efb8b28ce8.png)

Here's the same file opened in VSCode, which reports the error:
![Screen Shot 2019-11-04 at 11 22 46 PM](https://user-images.githubusercontent.com/271288/68178465-1ff80c00-ff5a-11e9-93cb-afa31afb3a32.png)

**Comment by jeffschwartz** [comment]
I did some sherlocking and discovered that eslint's no-trailing-spaces is conflicting with the reporting of errors if the error is at the end of the line, as missing semicolons would be. In the image below, I replaced the semicolon with a space, which violates the no-trailing-spaces rule, and both the missing semicolon and the trailing spaces errors are reported.
![Screen Shot 2019-11-05 at 12 48 51 AM](https://user-images.githubusercontent.com/271288/68181617-0eb4fc80-ff66-11e9-9b08-59e14734ffc2.png)

**Comment by jeffschwartz** [comment]
For the sake of clarity I edited my finding of having no trailing spaces at the end of a line interfering with reporting errors. I hope the information will help. I'm sorry but I don't know typescript well enough to attempt a pull request. Please let me know if there is anything else I can do to assist.

**Comment by chemzqm** [comment]
Reproduced.

**Comment by chemzqm** [comment]
Fixed on lastest coc.nvim.

**Comment by jeffschwartz** [comment]
Errors still don't show when at end of line
![Screen Shot 2019-11-05 at 8 09 37 AM](https://user-images.githubusercontent.com/271288/68210531-bbfa3580-ffa3-11e9-9cdb-021186a452ab.png)
in v1.2.2:
![Screen Shot 2019-11-05 at 8 08 39 AM](https://user-images.githubusercontent.com/271288/68210503-ac7aec80-ffa3-11e9-932f-6015594eaacf.png)

**Comment by fannheyward** [comment]
Checkout the last comment, it was fixed on coc.nvim, you need to upgrade coc.

**Comment by jeffschwartz** [comment]
Thank you @fannheyward and @chemzqm. Yes, the latest release is working since upgrading coc.nvim as suggested. I want to thank you for your awesome contribution and dedication.

**Comment by josegl** [comment]
How do you display that the file has errors in the vim's status line?

I have coc-eslint installed and working, but it only displays the errors and warnings where they are. So if the error is in the line N, the error only displays at line N, but in the status line anything indicates that there is any error, so if you don't have the N line in your view, you cannot see if there is an error unless you navigate the whole file.

Thank you.

**Comment by kanna99o** [comment]
Hi,

I'm using nvim 0.44 and I'm having the same problem that @jeffschwartz reported.

<img width="801" alt="Captura de Pantalla 2020-09-13 a la(s) 18 51 08" src="https://user-images.githubusercontent.com/20410974/93030733-a7db8780-f5fb-11ea-86e5-3b7d3d18b0e2.png">


As you can see, in line 1 there is a missing missing semicolon, but the undercurl isn't shown and the error report is given while hovering on line 2 instead of line 1. if I add an empty space to the end of the line (like in line 8), an underline indicating the error is shown.

However, if I add code with errors, the I get indication of those errors, and the indications of the previous errors aren't shown anymore (even though they appear in CocDiagnostic), like in the image below.

<img width="804" alt="Captura de Pantalla 2020-09-13 a la(s) 19 23 02" src="https://user-images.githubusercontent.com/20410974/93030740-ba55c100-f5fb-11ea-8f0f-16d3f6800da9.png">

Here are the current versions I'm using:

<img width="633" alt="Captura de Pantalla 2020-09-13 a la(s) 19 36 19" src="https://user-images.githubusercontent.com/20410974/93030749-d3f70880-f5fb-11ea-944d-ffaf9a1cbd70.png">

<img width="802" alt="Captura de Pantalla 2020-09-13 a la(s) 18 50 36" src="https://user-images.githubusercontent.com/20410974/93030758-deb19d80-f5fb-11ea-8311-578b3b6447ce.png">


I also attach the current .eslintrc from this project:

```javascript
{
  "plugins": ["prettier", "@typescript-eslint"],
  "extends": ["airbnb-typescript", "react-app", "prettier"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "settings": {
    "import/resolver": {
      "typescript": {
        "alwaysTryTypes": true
      }
    }
  },
  "rules": {
    "@typescript-eslint/indent": "off",
    "object-curly-spacing": ["warn", "always"],
    "no-unused-vars": [
      "warn",
      {
        "vars": "all",
        "args": "after-used"
      }
    ],
    "@typescript-eslint/no-unused-vars": [
      "warn",
      {
        "vars": "all",
        "args": "after-used"
      }
    ],
    "@typescript-eslint/no-explicit-any": [
      "error",
      {
        "ignoreRestArgs": true
      }
    ],
    "react/jsx-key": "error",
    "import/no-extraneous-dependencies": [
      "error",
      {
        "devDependencies": [
          "**/*.test.js",
          "**/*.test.jsx",
          "**/*.test.ts",
          "**/*.test.tsx",
          "src/tests/**/*"
        ]
      }
    ],
    "no-nested-ternary": "off",
    "react/jsx-props-no-spreading": "off",
    "import/prefer-default-export": "off",
    "react/jsx-boolean-value": ["error", "always"],
    "react/prop-types": "off",
    "react/jsx-wrap-multilines": ["error", { "declaration": false, "assignment": false }],
    "padding-line-between-statements": [
      "error",
      { "blankLine": "always", "prev": "import", "next": "*" },
      { "blankLine": "never", "prev": "import", "next": "import" },
      { "blankLine": "always", "prev": "multiline-block-like", "next": "multiline-block-like" },
      { "blankLine": "always", "prev": "*", "next": "return" },
      { "blankLine": "always", "prev": "class", "next": "*" },
      { "blankLine": "always", "prev": "*", "next": "class" },
      { "blankLine": "always", "prev": "function", "next": "*" },
      { "blankLine": "always", "prev": "*", "next": "function" },
      { "blankLine": "always", "prev": "multiline-const", "next": "*" },
      { "blankLine": "always", "prev": "*", "next": "multiline-const" },
      { "blankLine": "always", "prev": "multiline-let", "next": "*" },
      { "blankLine": "always", "prev": "*", "next": "multiline-let" }
    ]
  }
}
```

I hope, this info is useful to reproduce the issue. BTW, I have never had this kind of issues while viewing this project in VSCode.

Thanks.


PS: I also have an issue with the style of the underlines indicating the errors. With coc-eslint activated, they are just white straight lines, but if I deactivate coc-eslint, they are red and yellow undercurls for errors and warnings respectively (errors and warnings come from tsserver in that case) . No clue what could be causing the issue.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by xavierhazzardadmin** [comment]
> Fixed on lastest coc.nvim.

I'm having an issue like this. My errors just don't show up full stop. I've tried to debug it using the output channel and I still am unable to get it working in my typescript projects

**Comment by luisalcarasr** [comment]
I'm having this issue too.

**Comment by chemzqm** [comment]
Upgrade coc.nvim to should fix.
